
CREATE GENERATOR GEN_PAIS_ID;

/* Structure for the `PAIS` table :  */

CREATE TABLE PAIS (
  ID INTEGER NOT NULL,
  NOME VARCHAR(32) NOT NULL);


ALTER TABLE PAIS ADD PRIMARY KEY (ID);

/* Definition for the `BI_PAIS_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_PAIS_ID FOR PAIS
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(GEN_PAIS_ID, 1);
END^

SET TERM ; ^

/* Definition for the `GEN_PAIS_POPULACAO_ID` generator :  */

CREATE GENERATOR GEN_PAIS_POPULACAO_ID;

/* Structure for the `PAIS_POPULACAO` table :  */

CREATE TABLE PAIS_POPULACAO (
  ID INTEGER NOT NULL,
  ID_PAIS INTEGER NOT NULL,
  ANO SMALLINT NOT NULL,
  POPULACAO BIGINT NOT NULL);


ALTER TABLE PAIS_POPULACAO ADD PRIMARY KEY (ID);

/* Definition for the `BI_PAIS_POPULACAO_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_PAIS_POPULACAO_ID FOR PAIS_POPULACAO
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(GEN_PAIS_POPULACAO_ID, 1);
END^

SET TERM ; ^

/* Definition for the `GUID` domain :  */

CREATE DOMAIN GUID AS
  CHAR(16) CHARACTER SET OCTETS;

/* Structure for the `CLIENTE` table :  */

CREATE TABLE CLIENTE (
  ID GUID NOT NULL,
  NOME VARCHAR(64),
  ATIVO CHAR(1));


ALTER TABLE CLIENTE ADD PRIMARY KEY (ID);

/* Structure for the `PAIS_POPULACAO` table :  */

ALTER TABLE PAIS_POPULACAO ADD CONSTRAINT FK_PAIS_POPULACAO FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID);

/* Privileges for the `CLIENTE` :  */


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON CLIENTE TO SYSDBA WITH GRANT OPTION;


/* Privileges for the `PAIS` :  */


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON PAIS TO SYSDBA WITH GRANT OPTION;


/* Privileges for the `PAIS_POPULACAO` :  */


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON PAIS_POPULACAO TO SYSDBA WITH GRANT OPTION;

